'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Test3DConsole.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #version 400 core
        '''
        '''in vec2 pass_textureCoordinates;
        '''
        '''out vec4 out_Color;
        '''
        '''uniform sampler2D modelTexture;
        '''
        '''void main(void){	
        '''	vec4 textureColour = texture(modelTexture,pass_textureCoordinates);
        '''	if(textureColour.a&lt;0.9){
        '''		discard;
        '''	}
        '''	out_Color =  (texture(modelTexture,pass_textureCoordinates)
        '''
        '''}.
        '''</summary>
        Friend ReadOnly Property fragmentShader() As String
            Get
                Return ResourceManager.GetString("fragmentShader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #version 400 core
        '''
        '''in vec3 position;
        '''in vec2 textureCoordinates;
        '''in vec3 normal;
        '''
        '''out vec2 pass_textureCoordinates;
        '''
        '''uniform mat4 transformationMatrix;
        '''uniform mat4 projectionMatrix;
        '''uniform mat4 viewMatrix;
        '''
        '''void main(void){
        '''
        '''	vec4 worldPosition = transformationMatrix * vec4(position,1.0);
        '''	gl_Position = projectionMatrix * viewMatrix * worldPosition;
        '''	pass_textureCoordinates = textureCoordinates;
        '''	
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property vertexShader() As String
            Get
                Return ResourceManager.GetString("vertexShader", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
